name: build gatsby
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # 최신 버전으로 업데이트
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'yarn'   # 별도로 actions/cache를 안써도 yarn/npm 캐시 지원됨
      - name: Install dependencies
        run: yarn install --prod --pure-lockfile
      - name: Build
        run: yarn build --prefix-paths
        env:
          NODE_ENV: production
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: depoly
